<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="General Properties">
		<TargetFrameworks>net10.0;net9.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>OceanApocalypse.RSML.Abstractions.Diagnostics</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OceanApocalypse.RSML.Abstractions.Diagnostics</PackageId>
		<Title>RSML Diagnostics</Title>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML.Abstractions.Panic\RSML.Abstractions.Panic.csproj" />
	</ItemGroup>
</Project>