<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="General Properties">
		<TargetFrameworks>net10.0;net9.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>OceanApocalypse.RSML.Toolchain.Extensibility.Parsing</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OceanApocalypse.RSML.Toolchain.Extensibility.Parsing</PackageId>
		<Title>RSML Extensible Parsers</Title>
	</PropertyGroup>
</Project>