<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="General Properties">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>
		<RootNamespace>OceanApocalypse.RSML.Language.Lexing</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OceanApocalypse.RSML.Language.Lexing</PackageId>
		<Title>RSML Lexers</Title>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML.Abstractions\RSML.Abstractions.csproj" />
		<ProjectReference Include="..\RSML.Abstractions.Panic\RSML.Abstractions.Panic.csproj" />
		<ProjectReference Include="..\RSML.Abstractions.Diagnostics\RSML.Abstractions.Diagnostics.csproj" />
	</ItemGroup>
</Project>
