<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="General Properties">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>
		<RootNamespace>OceanApocalypse.RSML.Toolchain.Analysis</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OceanApocalypse.RSML.Toolchain.Analysis</PackageId>
		<Title>RSML Analyzers</Title>
	</PropertyGroup>
</Project>
