<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="General Properties">
		<TargetFrameworks>net10.0;net9.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>OceanApocalypse.RSML.Abstractions</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Label="NuGet Package Setup">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OceanApocalypse.RSML.Abstractions</PackageId>
		<Title>RSML Abstractions</Title>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RSML.Abstractions.Panic\RSML.Abstractions.Panic.csproj" />
		<ProjectReference Include="..\RSML.Abstractions.Diagnostics\RSML.Abstractions.Diagnostics.csproj" />
	</ItemGroup>
</Project>